var allCountriesJson = [
  {"Value": 108, "Name": "Afghanistan"},
  {"Value": 115, "Name": "Albania"},
  {"Value": 119, "Name": "Algeria"},
  {"Value": 4, "Name": "Andorra"},
  {"Value": 159, "Name": "Angola"},
  {"Value": 5, "Name": "Anguilla"},
  {"Value": 124, "Name": "Antigua and Barbuda"},
  {"Value": 6, "Name": "Argentina"},
  {"Value": 113, "Name": "Armenia"},
  {"Value": 7, "Name": "Aruba"},
  {"Value": 8, "Name": "Australia"},
  {"Value": 9, "Name": "Austria"},
  {"Value": 196, "Name": "Azerbaijan"},
  {"Value": 11, "Name": "Bahamas"},
  {"Value": 10, "Name": "Bahrain"},
  {"Value": 116, "Name": "Bangladesh"},
  {"Value": 12, "Name": "Barbados"},
  {"Value": 197, "Name": "Belarus"},
  {"Value": 13, "Name": "Belgium"},
  {"Value": 117, "Name": "Belize"},
  {"Value": 123, "Name": "Benin"},
  {"Value": 14, "Name": "Bermuda"},
  {"Value": 231, "Name": "Bhutan"},
  {"Value": 199, "Name": "Bolivia"},
  {"Value": 200, "Name": "Bosnia and Herzegovina"},
  {"Value": 15, "Name": "Botswana"},
  {"Value": 16, "Name": "Brazil"},
  {"Value": 17, "Name": "British Virgin Islands"},
  {"Value": 18, "Name": "Brunei"},
  {"Value": 109, "Name": "Bulgaria"},
  {"Value": 194, "Name": "Burkina Faso"},
  {"Value": 177, "Name": "Burma"},
  {"Value": 229, "Name": "Burundi"},
  {"Value": 201, "Name": "Cambodia"},
  {"Value": 158, "Name": "Cameroon"},
  {"Value": 243, "Name": "Canada - Alberta"},
  {"Value": 242, "Name": "Canada - British Columbia"},
  {"Value": 245, "Name": "Canada - Manitoba"},
  {"Value": 248, "Name": "Canada - New Brunswick"},
  {"Value": 251, "Name": "Canada - Newfoundland and Labrador"},
  {"Value": 258, "Name": "Canada - Northwest Territories"},
  {"Value": 249, "Name": "Canada - Nova Scotia"},
  {"Value": 246, "Name": "Canada - Ontario"},
  {"Value": 250, "Name": "Canada - Prince Edward Island"},
  {"Value": 247, "Name": "Canada - Quebec"},
  {"Value": 244, "Name": "Canada - Saskatchewan"},
  {"Value": 19, "Name": "Cape Verde"},
  {"Value": 20, "Name": "Cayman Islands"},
  {"Value": 118, "Name": "Central African Republic"},
  {"Value": 191, "Name": "Chad"},
  {"Value": 21, "Name": "Chile"},
  {"Value": 22, "Name": "China"},
  {"Value": 141, "Name": "Colombia"},
  {"Value": 138, "Name": "Congo, Democratic Republic of the"},
  {"Value": 192, "Name": "Congo, Republic of the"},
  {"Value": 23, "Name": "Costa Rica"},
  {"Value": 154, "Name": "Côte d'Ivoire"},
  {"Value": 24, "Name": "Croatia"},
  {"Value": 120, "Name": "Cuba"},
  {"Value": 240, "Name": "Curacao"},
  {"Value": 25, "Name": "Cyprus"},
  {"Value": 26, "Name": "Czech Republic"},
  {"Value": 27, "Name": "Denmark"},
  {"Value": 224, "Name": "Djibouti"},
  {"Value": 125, "Name": "Dominica"},
  {"Value": 28, "Name": "Dominican Republic"},
  {"Value": 29, "Name": "Ecuador"},
  {"Value": 134, "Name": "Egypt"},
  {"Value": 237, "Name": "EHEA"},
  {"Value": 121, "Name": "El Salvador"},
  {"Value": 253, "Name": "Equatorial Guinea"},
  {"Value": 204, "Name": "Eritrea"},
  {"Value": 30, "Name": "Estonia"},
  {"Value": 135, "Name": "Ethiopia"},
  {"Value": 32, "Name": "Fiji"},
  {"Value": 33, "Name": "Finland"},
  {"Value": 34, "Name": "France"},
  {"Value": 35, "Name": "French Guiana"},
  {"Value": 193, "Name": "Gabon"},
  {"Value": 206, "Name": "Gambia"},
  {"Value": 110, "Name": "Georgia"},
  {"Value": 37, "Name": "Germany"},
  {"Value": 151, "Name": "Ghana"},
  {"Value": 39, "Name": "Greece"},
  {"Value": 126, "Name": "Grenada"},
  {"Value": 40, "Name": "Guadeloupe"},
  {"Value": 189, "Name": "Guatemala"},
  {"Value": 188, "Name": "Guinea"},
  {"Value": 127, "Name": "Guyana"},
  {"Value": 187, "Name": "Haiti"},
  {"Value": 186, "Name": "Honduras"},
  {"Value": 41, "Name": "Hong Kong"},
  {"Value": 42, "Name": "Hungary"},
  {"Value": 43, "Name": "Iceland"},
  {"Value": 44, "Name": "India"},
  {"Value": 45, "Name": "Indonesia"},
  {"Value": 114, "Name": "Iran"},
  {"Value": 147, "Name": "Iraq"},
  {"Value": 46, "Name": "Ireland"},
  {"Value": 47, "Name": "Israel"},
  {"Value": 48, "Name": "Italy"},
  {"Value": 49, "Name": "Jamaica"},
  {"Value": 50, "Name": "Japan"},
  {"Value": 51, "Name": "Jordan"},
  {"Value": 104, "Name": "Kazakhstan"},
  {"Value": 107, "Name": "Kenya"},
  {"Value": 235, "Name": "Kosovo"},
  {"Value": 207, "Name": "Kuwait"},
  {"Value": 105, "Name": "Kyrgyzstan"},
  {"Value": 208, "Name": "Laos"},
  {"Value": 52, "Name": "Latvia"},
  {"Value": 185, "Name": "Lebanon"},
  {"Value": 184, "Name": "Lesotho"},
  {"Value": 183, "Name": "Liberia"},
  {"Value": 209, "Name": "Libya"},
  {"Value": 53, "Name": "Liechtenstein"},
  {"Value": 54, "Name": "Lithuania"},
  {"Value": 55, "Name": "Luxembourg"},
  {"Value": 210, "Name": "Macau"},
  {"Value": 157, "Name": "Madagascar"},
  {"Value": 182, "Name": "Malawi"},
  {"Value": 56, "Name": "Malaysia"},
  {"Value": 57, "Name": "Maldives"},
  {"Value": 181, "Name": "Mali"},
  {"Value": 58, "Name": "Malta"},
  {"Value": 59, "Name": "Martinique"},
  {"Value": 180, "Name": "Mauritania"},
  {"Value": 179, "Name": "Mauritius"},
  {"Value": 61, "Name": "Mexico"},
  {"Value": 215, "Name": "Micronesia"},
  {"Value": 164, "Name": "Moldova"},
  {"Value": 106, "Name": "Mongolia"},
  {"Value": 220, "Name": "Montenegro"},
  {"Value": 62, "Name": "Montserrat"},
  {"Value": 146, "Name": "Morocco"},
  {"Value": 156, "Name": "Mozambique"},
  {"Value": 178, "Name": "Myanmar"},
  {"Value": 63, "Name": "Namibia"},
  {"Value": 176, "Name": "Nepal"},
  {"Value": 64, "Name": "Netherlands"},
  {"Value": 65, "Name": "Netherlands Antilles"},
  {"Value": 67, "Name": "New Zealand"},
  {"Value": 175, "Name": "Nicaragua"},
  {"Value": 174, "Name": "Niger"},
  {"Value": 129, "Name": "Nigeria"},
  {"Value": 163, "Name": "North Macedonia"},
  {"Value": 68, "Name": "Norway"},
  {"Value": 66, "Name": "Oman"},
  {"Value": 112, "Name": "Pakistan"},
  {"Value": 233, "Name": "Palestine"},
  {"Value": 166, "Name": "Panama"},
  {"Value": 173, "Name": "Papua New Guinea"},
  {"Value": 172, "Name": "Paraguay"},
  {"Value": 149, "Name": "Peru"},
  {"Value": 69, "Name": "Philippines"},
  {"Value": 71, "Name": "Poland"},
  {"Value": 72, "Name": "Portugal"},
  {"Value": 225, "Name": "Puerto Rico"},
  {"Value": 73, "Name": "Qatar"},
  {"Value": 74, "Name": "Reunion"},
  {"Value": 153, "Name": "Romania"},
  {"Value": 75, "Name": "Russia"},
  {"Value": 171, "Name": "Rwanda"},
  {"Value": 76, "Name": "Samoa"},
  {"Value": 150, "Name": "Saudi Arabia"},
  {"Value": 221, "Name": "Scotland"},
  {"Value": 218, "Name": "Senegal"},
  {"Value": 165, "Name": "Serbia"},
  {"Value": 169, "Name": "Sierra Leone"},
  {"Value": 77, "Name": "Singapore"},
  {"Value": 78, "Name": "Slovak Republic"},
  {"Value": 79, "Name": "Slovenia"},
  {"Value": 219, "Name": "Somalia"},
  {"Value": 81, "Name": "South Africa"},
  {"Value": 82, "Name": "South Korea"},
  {"Value": 261, "Name": "South Sudan"},
  {"Value": 83, "Name": "Spain"},
  {"Value": 155, "Name": "Sri Lanka"},
  {"Value": 85, "Name": "St. Kitts and Nevis"},
  {"Value": 86, "Name": "St. Lucia"},
  {"Value": 130, "Name": "St. Maarten"},
  {"Value": 131, "Name": "St. Vincent and The Grenadines"},
  {"Value": 144, "Name": "Sudan"},
  {"Value": 132, "Name": "Suriname"},
  {"Value": 168, "Name": "Swaziland"},
  {"Value": 88, "Name": "Sweden"},
  {"Value": 89, "Name": "Switzerland"},
  {"Value": 213, "Name": "Syria"},
  {"Value": 90, "Name": "Taiwan"},
  {"Value": 212, "Name": "Tajikistan"},
  {"Value": 142, "Name": "Tanzania"},
  {"Value": 91, "Name": "Thailand"},
  {"Value": 92, "Name": "Togo"},
  {"Value": 93, "Name": "Tonga"},
  {"Value": 94, "Name": "Trinidad and Tobago"},
  {"Value": 95, "Name": "Tunisia"},
  {"Value": 96, "Name": "Turkiye"},
  {"Value": 222, "Name": "Turkmenistan"},
  {"Value": 97, "Name": "Turks and Caicos Islands"},
  {"Value": 145, "Name": "Uganda"},
  {"Value": 98, "Name": "Ukraine"},
  {"Value": 99, "Name": "United Arab Emirates"},
  {"Value": 3, "Name": "United Kingdom"},
  {"Value": 2, "Name": "United States"},
  {"Value": 100, "Name": "Uruguay"},
  {"Value": 111, "Name": "Uzbekistan"},
  {"Value": 228, "Name": "Vatican City"},
  {"Value": 101, "Name": "Venezuela"},
  {"Value": 102, "Name": "Vietnam"},
  {"Value": 152, "Name": "Yemen"},
  {"Value": 162, "Name": "Yugoslavia"},
  {"Value": 161, "Name": "Zambia"},
  {"Value": 160, "Name": "Zimbabwe"}
];
